WEBsinjyuku/meister-hackers

- Dockerfile
- config/database.yml
- docker-compose.yml
#39 
30m/30m
config/database.yml
docker-compose.yml
Dockerfile
- rails db:createでDB作成をするために、role=postgresを設定したかったので。
- Docker(docker-compse)の導入が目的
> Rails開発環境導入 with Docker

- app/models/post.rb
- app/models/user.rb
- db/migrate/20190127045138_add_columns_to_posts.rb
- db/schema.rb
- spec/factories/posts.rb
- spec/factories/users.rb
- spec/models/post_spec.rb
親issue #42 
20m/20m
xxH/xxH
以下の部分
> - [ ] Postテーブルに，title, description を追加し，validationをつける
> Feature/add columns to post#42

- app/controllers/posts_controller.rb
- app/views/posts/_form.html.slim
- app/views/posts/edit.html.slim
- app/views/posts/new.html.slim
- config/routes.rb
- spec/controllers/posts_controller_spec.rb
#42 
1.5h / 1.5h
xxH/xxH
> コントローラ (new, edit, create, updateを作成) とルーティング
title と description 用のフォーム作成
controllerと最低限のviewの作成，routeの設定
> Feature/controller routes#42

- app/models/post.rb
- app/models/project.rb
- db/migrate/20190127105228_create_projects.rb
- db/schema.rb
- spec/factories/projects.rb
- spec/models/project_spec.rb
#42 
30m/30m
xxH/xxH
> - [ ] Postテーブル or Project テーブルに url or repo_name を追加し，validationをつける
この部分
実際は project テーブルを作成し，post と紐付けた
> refs #create project table

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.css
- app/views/layouts/_navbar.html.slim
- app/views/layouts/application.html.slim
#96 
30m/3h
ナビゲーションバーを追加で作成
[![Screenshot from Gyazo](https://gyazo.com/918eeb7f0aa251fda3f9f91003bc0800/raw)](https://gyazo.com/918eeb7f0aa251fda3f9f91003bc0800)
目的はLT会などで仮でいいので開発画面を見せたいため
後日、より正確なものに修正したい
> Feature#add navbar#96

- app/views/posts/index.html.slim
#104 
7.0h / 10.0h
- index.html.slim（変更）
- application.html.slim（変更）
１件目がタグ（Topics）と説明文（description）があるバージョン
２件目はタグと説明文がないバージョン
Vue.js（Mustache）を適用する前のレイアウト確認。
ローカル環境で動作させる際は、application.html.slimに下記CDNを追加して下さい。
**link rel="stylesheet" href="https://bulma.io/css/bulma-docs.min.css"**
CDNがないと、下記イメージのレイアウトになります。（タグの描画ができない）
> プロジェクト一覧画面-固定HTMLでの画面イメージ作成

- app/controllers/profiles_controller.rb
- app/javascript/components/molecules/UserPost.vue
- app/javascript/components/molecules/UserProfile.vue
- app/javascript/components/organisms/MyPage.vue
- app/javascript/components/organisms/MyPageForm.vue
- app/javascript/packs/users/edit.vue.js
- app/views/users/edit.html.slim
- config/routes.rb
- package.json
- spec/factories/profiles.rb
#119 
[![Screenshot from Gyazo](https://gyazo.com/c3f6d8b4dc44a17dc405379c36b9e6e5/raw)](https://gyazo.com/c3f6d8b4dc44a17dc405379c36b9e6e5)
> マイページ(edit)

- Gemfile
- Gemfile.lock
- config/initializers/rollbar.rb
> Rollbarの導入

- app/assets/stylesheets/application.css
- app/views/layouts/_navbar.html.slim
#96 
30m/3h
nabvarを仮実装。あとはロゴと実装のデータを待つのみ
色とマージンボタンの距離は後で微調整。
ロゴが間に合わない場合は左辺青いスペースは削除予定
> navbarのレイアウト調整

- app/controllers/posts_controller.rb
- app/models/post.rb
- app/models/user.rb
- db/migrate/20190227220130_add_nickname_to_users.rb
- db/migrate/20190227222145_add_owner_to_posts.rb
- db/schema.rb
- spec/factories/posts.rb
- spec/factories/users.rb
- spec/models/post_spec.rb
#212 
* post tableに owner column追加
* user tableに nickname追加
> Post create バク修正

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/models/post.rb
- app/models/user.rb
- app/views/layouts/application.html.slim
- app/views/posts/show.html.slim
- spec/factories/posts.rb
- spec/factories/users.rb
- spec/models/post_spec.rb
#209 
turbolink廃止
vue.jsの機能と競合するため
> vueコンポーネントを表示できるように修正(Turbolink廃止)

- config/routes.rb
#238 
お騒がせしました。routes.ebへの環境判断用のifを忘れてました！
> routingにenv.production?追加

- app/views/posts/index.html.slim
> プロジェクト新規投稿コメントアウト。フッター修正

- app/assets/stylesheets/postsshow.css
- app/views/posts/_form.html.slim
#42
投稿のポストの幅
ポストが長いと画面が少し見にくいと感じたので提案修正
> 新規投稿部分修正#42

- app/assets/stylesheets/postsshow.css
- app/views/posts/show.html.slim
to close #223 
15m
- posts#showページにリポジトリURLを追加
- デザイン微修正
> posts#showページにリポジトリURLを追加

- app/assets/stylesheets/application.css
- app/views/errors/error_404.html.slim
#279 
1h/1.5h
error_404 デザイン追加
以下参照
https://github.com/WEBsinjyuku/meister-hackers/issues/279#issuecomment-470454378
デザインがなかったので
PR遅れてすみません！お願いします！
> error_404 add

- app/assets/stylesheets/postsshow.css
- app/controllers/profiles_controller.rb
- app/javascript/components/organisms/MessageBoard.vue
- app/javascript/components/organisms/MyPageForm.vue
- app/views/posts/show.html.slim
#315
#312
#306
2h/2h
3つのissue
正直IF文ちょっと記述として不合理かと思うので他にいい方法あれば教えてください
> Bugs#posts/show edit#306

- app/views/posts/show.html.slim
> 非ログイン時も募集停止見えるように修正

- app/assets/stylesheets/posts_form.css
- app/views/posts/_form.html.slim
170
- posts#new/edit時の、投稿/キャンセルボタンのデザインとレイアウトを修正
> デザイン再適応[Show Post View with Button (show.html.slim, _form.html.slim)]

- app/controllers/profiles_controller.rb
- app/javascript/components/molecules/UserProfile.vue
- app/javascript/components/organisms/MyPage.vue
- app/javascript/components/organisms/MyPageForm.vue
- app/models/post.rb
- config/routes.rb
- spec/factories/posts.rb
- spec/models/post_spec.rb
#244 
* 応急処置的な修正ですが､user editの不正アクセスは user indexにリダイレクトするようにしました。
* 自分のプロファイルのときだけ編集ボタンを有効にしました。
> Bugfix#244 user edit画面の権限まわり

- app/javascript/components/organisms/MessageBoard.vue
> 掲示板コメント 空白投稿をガード

- config/webpack/production.js
#344 
1.0h / 0.5h
webpack.production.js
VueコンポーネントのCSS読込設定
CSS読込設定が読み込まれていないため。
ローカルでProductionモードで実行していないので、確証はないですが基本的にこれでよいはず。
rails serverの再起動も行う予定。
> Prioduction環境でのVueコンポーネント CSS読込設定

- app/assets/stylesheets/top.css
- app/views/home/top.html.slim
[![Screenshot from Gyazo](https://gyazo.com/222f0cc11d736f689077cf8bbfd634e7/raw)](https://gyazo.com/222f0cc11d736f689077cf8bbfd634e7)
・LP画面からposts/showにログインしないと遷移しないためLP画面にposts/showへのリンクボタンを設置
本来はボタンではなく「さあ仲間とともに成長しよう」の下にテキスト形式の方がいいかもしれない
急造でルートを作成
> ログインしないでみるbtn設置
